#!/bin/bash
source $(dirname $0)/commonEnv
az appservice plan create --name $AZ_APP_SERVICE_PLAN --resource-group $AZ_RESOURCE_GROUP --sku S1 --is-linux

az functionapp create \
    --name $AZ_FUNCTION_APP_NAME \
    --storage-account $AZ_STORAGE_ACCOUNT \
    --resource-group $AZ_RESOURCE_GROUP \
    --plan $AZ_APP_SERVICE_PLAN \
    --deployment-container-image-name $DOCKER_IMAGE_NAME

storageConnectionString=$(az storage account show-connection-string --resource-group $AZ_RESOURCE_GROUP --name $AZ_STORAGE_ACCOUNT --query connectionString --output tsv)

az functionapp config appsettings set \
    --name $AZ_FUNCTION_APP_NAME \
    --resource-group $AZ_RESOURCE_GROUP \
    --settings \
        AzureWebJobsDashboard=$storageConnectionString \
        AzureWebJobsStorage=$storageConnectionString \
        WORKERS__NODE__DEBUG=0.0.0.0:5858 \
        APPSVC_TUNNEL_PORT=5858

az webapp log config --name $AZ_FUNCTION_APP_NAME --resource-group $AZ_RESOURCE_GROUP --docker-container-logging filesystem
