#!/bin/bash

DOCKER_IMAGE_NAME=mrcrane/azure-functions-node-remotedebug:dev-jessie-patched

AZ_SUBSCRIPTION=ce678eba-8ab3-4a0c-9610-97fee4ee6b34 # Ranjith Linux Test Sub
AZ_LOCATION=centraluseuap
AZ_NAME=micran-functions-remotedebug
# AZ_SUBSCRIPTION=49a56e80-d07f-408b-ac5e-361b1450b875 # F12 Development
# AZ_LOCATION=westus2
# AZ_NAME=micran-functions-docker

# For convenience, name all these things the same
AZ_RESOURCE_GROUP=$AZ_NAME
AZ_APP_SERVICE_PLAN=$AZ_NAME
AZ_FUNCTION_APP_NAME=$AZ_NAME

# Storage account names have some different rules
AZ_NAME_NODASHES=${AZ_NAME//-/}
AZ_NAME_NODASHES_TRUNCATED=${AZ_NAME_NODASHES:0:24}
AZ_STORAGE_ACCOUNT=$AZ_NAME_NODASHES_TRUNCATED

set -x
